### ISSUE TITLE
Unexpected error, unable to continue

### ISSUE THREAD

**Issue by Peter-Schorn** [fwal/setup-swift#229]
**Describe the bug**
I received an error in multiple jobs in the workflow for my [RegularExpressions](https://github.com/Peter-Schorn/RegularExpressions/actions/runs/891352626) library (commit: c0dd27d):
```
name: Swift

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.0", "5.1", "5.2", "5.3", "5.4"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v2
      - name: Build
        run: swift build --build-tests
      - name: Run tests
        run: swift test
```
Here is the output of some of the jobs that failed:

### Swift 5.0 on ubuntu-latest

Set up job
```
Current runner version: '2.278.0'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210524.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210524.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210524.1
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Issues: write
  Metadata: read
  Packages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'fwal/setup-swift@v1'
Download action repository 'actions/checkout@v2'
```

Run fwal/setup-swift@v1
```
Run fwal/setup-swift@v1
  with:
    swift-version: 5.0
/usr/bin/gpg --import /home/runner/work/_temp/4f1928c9-cbb8-46a3-aa8f-d68335288a81
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
gpg: key D441C977412B37AD: public key "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" imported
gpg: key 9F597F4D21A56D5F: public key "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: key 63BC1CFE91D306C6: public key "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: key EF5430F071E1B235: public key "Swift 4.x Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: key 7638F1FB2B2B08C4: public key "Swift Automatic Signing Key #2 <swift-infrastructure@swift.org>" imported
gpg: key 925CC1CCED3D1561: public key "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" imported
gpg: key FAF6989E1BC16FEA: public key "Swift Automatic Signing Key #3 <swift-infrastructure@swift.org>" imported
gpg: key 925CC1CCED3D1561: "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" 1 new signature
gpg: Total number processed: 8
gpg:               imported: 7
gpg:         new signatures: 1
/usr/bin/gpg --keyserver hkp://pool.sks-keyservers.net --refresh-keys Swift
gpg: refreshing 7 keys from hkp://pool.sks-keyservers.net
gpg: key FAF6989E1BC16FEA: "Swift Automatic Signing Key #3 <swift-infrastructure@swift.org>" not changed
gpg: key 925CC1CCED3D1561: "Swift 5.x Release Signing Key <swift-infrastructure@swift.org>" not changed
gpg: key 7638F1FB2B2B08C4: "Swift Automatic Signing Key #2 <swift-infrastructure@swift.org>" not changed
gpg: key EF5430F071E1B235: "Swift 4.x Release Signing Key <swift-infrastructure@swift.org>" not changed
gpg: key 63BC1CFE91D306C6: "Swift 3.x Release Signing Key <swift-infrastructure@swift.org>" not changed
gpg: key 9F597F4D21A56D5F: "Swift 2.2 Release Signing Key <swift-infrastructure@swift.org>" not changed
gpg: key D441C977412B37AD: "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" not changed
gpg: Total number processed: 7
gpg:              unchanged: 7
Error: Unexpected error, unable to continue. Please report at https://github.com/fwal/setup-swift/issues
Unexpected HTTP response: 404
Stacktrace:
Error: Unexpected HTTP response: 404
    at /home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:8816:25
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/fwal/setup-swift/v1/dist/index.js:8721:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The "Swift 5.1 on ubuntu-latest" job failed with the same error.

The "Swift 5.1 on macos-latest" and "Swift 5.2 on macos-latest" jobs also failed, although the cause of the failures may be unrelated to this action because they occurred in the "Build" step. Nevertheless, I would appreciate any help in determining the cause of the failures.

**I have uploaded a zip file of the full logs on [Google Drive](https://drive.google.com/file/d/1o0RufxpiCJf8ipptcDqvU5ULcTy4TV2Z/view?usp=sharing).**

### Summary
<img width="260" alt="Screen Shot 2021-05-30 at 8 04 05 PM" src="https://user-images.githubusercontent.com/58197311/120126530-31c78280-c182-11eb-8ff3-6fcca772c455.png">

### Edit

I just tested the following jobs:
```
jobs:
  test_macOS:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test

  test_linux:
    strategy:
      matrix:
        image: ["swift:5.0", "swift:5.1", "swift:5.2", "swift:5.3", "swift:5.4"]
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
```
All of these competed successfully, proving that my library *does* compile for Swift 5.0-5.4 on Linux and swift 5.3 on macOS.
