### ISSUE TITLE
Support trunk and dev snapshots

### ISSUE THREAD

**Issue by fwal** [fwal/setup-swift#98]
Trunk and dev releases should be supported.

Suggested api:
```yml
- uses: fwal/setup-swift@v1
  with:
    swift-version: "trunk"
```
and
```yml
- uses: fwal/setup-swift@v1
  with:
    swift-version: "5.3-dev"
```
