### ISSUE TITLE
2.0 API changes

### ISSUE THREAD

**Issue by fwal** [fwal/setup-swift#99]
_List of suggested changes to the API_

- Rename `swift-version` input to `swift`
```yml
- uses: fwal/setup-swift@v2
  with:
    swift: "5.2.4"
```
